openapi: 3.0.0
info:
  description: This is API for Bookstore where user can search books and buy them
  version: "1.0.0"
  title: Simple Bookstore API
tags:
  - name: auth
    description: Authentication endpoints for user
  - name: books
    description: Books endpoints for searching and get information
  - name: transactions
    description: Transactions endpoints for get history and get active transaction
servers:
  - url: https://example.com/api
paths:
  /auth/login:
    $ref: 'paths/auth/login.yml'
  /auth/register:
    $ref: 'paths/auth/register.yml'
components:
  schemas:
    User:
      $ref: 'schemas/user.yml'
    Book:
      $ref: 'schemas/book.yml'
  securitySchemes:
    JsonWebToken:
      type: http
      scheme: bearer